services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gaming_social_network
    ports:
      - "5432:5432"
  rails:
    build: .
    container_name: rails
    command: bin/dev
    volumes:
      - ${PWD}:/gaming_social_network
      - ruby-gems:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  ruby-gems:
  db-data:
